### ISSUE TITLE
Example code/documentation on running NoPFS in distributed training

### ISSUE THREAD

**Issue by mengwanguc** [spcl/NoPFS#1]
Hi,

Thanks for the great work!

I'm wondering if there is any example code or documentation on how to set up and run NoPFS in distributed training?

Thanks,
Meng

**Comment by ndryden** [comment]
You can take a look at the ResNet-50 benchmark, which includes distributed training support. Hopefully that helps!

**Comment by SunMinqiu** [comment]
Hi,

Thanks for the great work!

When I runnning this project, there is still a CMake Error: 
The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libconfig
    linked by target "hdmlp" in directory /mnt/d/Code Running/NoPFS/libhdmlp

after I export the following environment variables before running the install script, like:
export CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu:
export CPATH=/usr/include:


Thanks,
Minqiu
