### ISSUE TITLE
Question about libconfig

### ISSUE THREAD

**Issue by SunMinqiu** [spcl/NoPFS#2]
Hi,

Thanks for the great work!

When I runnning this project, there is still a CMake Error:
The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libconfig
linked by target "hdmlp" in directory /mnt/d/Code Running/NoPFS/libhdmlp

after I export the following environment variables before running the install script, like:
export CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu:
export CPATH=/usr/include:

Thanks,
Minqiu

**Comment by ndryden** [comment]
That looks like CMake is failing to find `libconfig`. Its CMake is honestly kind of broken, but you should be able to make it work by either adding the directory containing the libconfig CMake config to `CMAKE_PREFIX_PATH`, or directly setting the relevant library and include directories.
